### ISSUE TITLE
Badge for apps from Work Profile....

### ISSUE THREAD

**Issue by TheMysticS** [d4rken-org/mystic-permissions#18]
Please add the briefcase icon used by Android for apps installed in Work Profile.

**Comment by d4rken** [comment]
Listing all profiles will not be possible, see #20 
Showing an icon for apps that HAVE another profile, might be possible.

**Comment by d4rken** [comment]
Sadly this does not work out either.
My idea was to check if the device supports work profiles and if it does, query the GIDs for a package, if there is more than one, assume that this app is cloned to a work profile.
After trying a few different cloned packages now, they all had a single GID and not multiple.

So I currently only see root or being a profile owner and like #20 I see both as out of scope for this app, sorry :frowning:
