### ISSUE TITLE
Link to System Settings

### ISSUE THREAD

**Issue by TheMysticS** [d4rken-org/mystic-permissions#22]
Under App Details, if I click on any permission, it opens a new page listing all apps having that permission. Clicking on any app opens the app details page showing all permissions for that app. So it keeps going back and forth within the app.

Instead of doing this, if user clicks on a permission that can be modified, he should instead be taken to the System Settings page for that app, so he can make any change, as required.

In this context, it would be nice if clicking on the back button would take the user directly back to this app, to the same place from where he launched the System Settings page. It would be inconvenient if the back button starts going one level up in System Settings with each click, until the user is on the home screen, and then he has to launch this app.

I'm not sure if this is something under developer control, but this is something very convenient to have.

**Comment by d4rken** [comment]
Maybe for permissions that can be changed, the granted/denied icon looks a bit different? And pressing it open the system settings. While pressing the whole row still opens the permission details?

**Comment by TheMysticS** [comment]
> Maybe for permissions that can be changed, the granted/denied icon looks a bit different? And pressing it open the system settings. While pressing the whole row still opens the permission details?

Perfect 👍

**Comment by d4rken** [comment]
I currently can't find a way to open anything else besides the details page of an app :frowning:

**Comment by TheMysticS** [comment]
Installed apps are able to launch the Special Access Settings page whenever a permission is required. Not just that, they scroll directly to their own position in the page to make it easy for the user to enable the permission.

Does it give you any hint?

**Comment by d4rken** [comment]
Can you give me an example app and/or permission?

**Comment by TheMysticS** [comment]
> Can you give me an example app and/or permission?

SD Maid itself for All Files access. Or Usage Data access.

**Comment by d4rken** [comment]
Ah good point :sweat_smile: will have to check if the intent can be used if not asking for the permission.

**Comment by d4rken** [comment]
I've introduced the abstraction `PermissionAction` which we can now use to give each permission a custom action, e.g. open their respective system screen if that is possible:

https://github.com/d4rken-org/mystic-permissions/blob/ff577d72e866004f1db57175a70ddcf1e76a6a81/app/src/main/java/eu/darken/myperm/permissions/core/PermissionAction.kt

So we have to add each permission and it's action here:
https://github.com/d4rken-org/mystic-permissions/blob/ff577d72e866004f1db57175a70ddcf1e76a6a81/app/src/main/java/eu/darken/myperm/permissions/core/known/AKnownPermissions.kt

Currently it all defaults to `None`

**Comment by d4rken** [comment]
Closing in favor of more specific tickets. Base architecture is available now.
