### ISSUE TITLE
OEM App Store Labels

### ISSUE THREAD

**Issue by TheMysticS** [d4rken-org/mystic-permissions#27]
> vivo app store: `com.vivo.appstore` oppo app store: `com.oppo.market` Huawei app store: `com.huawei.appmarket` Samsung app store: `com.sec.android.app.samsungapps` Xiaomi app store: `com.xiaomi.mipicks`

I've added these, see:
https://github.com/d4rken/mystic-permissions/blob/c5551253f7b35b572e9a2975f901fd6c025ad9ca/app/src/main/java/eu/darken/myperm/apps/core/known/ZKnownPkgs.kt#L14-L40

_Originally posted by @d4rken in https://github.com/d4rken/mystic-permissions/issues/5#issuecomment-1186614560_

Can you use the official names for the Stores like this:

1. Samsung Galaxy Store
2. Xiaomi GetApps
3. Vivo V-AppStore
4. Oppo AppMarket

The name for Store from Huawei is likely correct, but I'm not sure.

**Comment by dragonGod97677** [comment]
Oppo's app market app label is just "App Market"

**Comment by dragonGod97677** [comment]
Vivo is "V-AppStore"

**Comment by TheMysticS** [comment]
> Oppo's app market app label is just "App Market"

I'm adding the brand name in front just to remove any ambiguity. For example, Galaxy Store is the name of the Store from Samsung. But I added the brand name in front just to make that very clear.

**Comment by TheMysticS** [comment]
> Vivo is "V-AppStore"

I have edited the OP to include the correct names. Thanks.
