### ISSUE TITLE
[Improvement needed]: Sideloaded Apps

### ISSUE THREAD

**Issue by TheMysticS** [d4rken-org/mystic-permissions#28]
Apps that came pre-installed, show the installer source as 'Manual Install' with the human icon. And they are being included with Sideloaded Apps.

They are not sideloaded by the user. Apps sideloaded by the user will have a definitive source, even if installed via ADB, isn't it?

Sideloaded apps are strictly those that the user himself has installed. Can you make this filter work like this?

**Comment by TheMysticS** [comment]
Also, 'Manual Install' doesn't sound right. If there is no way to identify the source, can it be assumed to be pre-installed by the OEM? If that is true, then a label called 'Pre-installed by OEM' sounds good.

**Comment by d4rken** [comment]
I've changed the name to "unknown installer".
The data is just `null` there is no way to tell where it came from in these cases.
ADB doesn't set a source by default either, you have to use extra options.
