### ISSUE TITLE
Additional Sort Category: Install Source

### ISSUE THREAD

**Issue by TheMysticS** [d4rken-org/mystic-permissions#30]
In the Sort categories (in Apps tab), can we have an additional sort category called 'Install Source'?

This will sort all apps by their install sources. 

[Screenshot_2022-07-18-10-49-16-56_ce34de6323cfaeb7a2880d42987990b1](https://user-images.githubusercontent.com/54448474/179449816-33117daf-4bff-4d0c-8cd0-abdb93c4fc14.jpg)

It will basically list all the sources in collapsed form:

1. Google Play Store
2. OEM Store (replace with correct Store Name)
3. Sideloaded Apps

User can expand each category to view apps installed using each source. Sideloaded apps will be further sorted by the Installer Source, i.e. all apps installed using SAI will be sorted together alphabetically, those installed using Chrome will appear together, those installed using PC/ ADB will appear together, etc.

In fact, a sub-filter by source in this section would be great too.

**Comment by TheMysticS** [comment]
This is not showing up in v.0.3.0. Are you yet to release the build with this change?

In this context, is there a way to see whether a new commit is already included in any of the existing releases or not?

**Comment by d4rken** [comment]
You can see the list of commits on `main` here:
https://github.com/d4rken-org/mystic-permissions/commits/main

Each release is based on a tag:
https://github.com/d4rken-org/mystic-permissions/releases

Sadly GitHub doesn't show tags in the commit history.
You can check the hash of the tag, e.g. for 0.3.0 `fa95a39`

![Screenshot from 2022-07-20 13-31-25](https://user-images.githubusercontent.com/1439229/179971598-0ff6cc2a-5506-4a10-8f45-3cb150439055.png)

But usually you can also just click the commit.
When clicking  `closed this as completed in 74c0d73` you see this:
![Screenshot from 2022-07-20 13-32-01](https://user-images.githubusercontent.com/1439229/179971758-7a5081db-5a53-465e-88aa-b23c93f30032.png)
so this change is only in the `main` branch.

If we check this closed issue:
https://github.com/d4rken-org/mystic-permissions/issues/42#event-7022093010

We see it's in main and the tag `v0.3.0`.

![Screenshot from 2022-07-20 13-33-30](https://user-images.githubusercontent.com/1439229/179972000-44b12ae6-5234-4bc5-b141-b0d96a1e4b9f.png)
