### ISSUE TITLE
[Enhancement]: Rescan/ Refresh Button

### ISSUE THREAD

**Issue by TheMysticS** [d4rken-org/mystic-permissions#31]
Please add a 'Rescan' or 'Refresh' button to force the app to rescan all packages and permissions.

I installed a new app and it was not showing up no matter how many different sort/ filter options I tried. I had to Force Stop this app and relaunch it. The new app then showed up.

**Comment by d4rken** [comment]
Done, should also refresh automatically on app install/uninstall now.
