### ISSUE TITLE
[NEW FEATURE]: Sibling Details with App Link

### ISSUE THREAD

**Issue by TheMysticS** [d4rken-org/mystic-permissions#34]
Under App Details where you show Siblings for apps with SharedUserID, can you also show the app icons for apps using the same IDs (Siblings)?

The icons themselves will be links that open the App Details page of the respective apps.

Something like this:

![Siblings](https://user-images.githubusercontent.com/54448474/179541374-e19222a2-f414-4776-8cd1-d20d8d78fdf1.png)

**Comment by d4rken** [comment]
Does it not show if you "expand" the card?
Should only collapse for > 5 items though.
Can you make a bug ticket?

**Comment by TheMysticS** [comment]
> Does it not show if you "expand" the card? Should only collapse for > 5 items though. Can you make a bug ticket?

The screenshot above already shows it in expanded form. The Siblings are not showing up. I'll create a new ticket for this bug.
