### ISSUE TITLE
System App Indicator

### ISSUE THREAD

**Issue by TheMysticS** [d4rken-org/mystic-permissions#35]
In the Apps tab, can we show the System Apps with some sort of an indicator?

Some suggestions:

1. The whole row for System apps will have a very light (very faint) orange background.

2. There will be a small circular orange coloured dot on the top right corner of the app icon.

3. 'System' text would be written underneath the app icon.

**Comment by TheMysticS** [comment]
Option 2 would be my preferred choice to maintain UI consistency.

**Comment by TheMysticS** [comment]
Can you use Orange/ Red colour for the icon?

**Comment by TheMysticS** [comment]
Reopening this as there is not much discussion.

**Comment by d4rken** [comment]
> Can you use Orange/ Red colour for the icon?

I don't want to add too many colors to the tags, shouldn't look like a rainbow. It being red would distract too much imho.

> Please also check the alignment. It would look nice if it is centred right below the app icon.

It's part of the flexbox of the tag row and will move to make space depending on the amount of icons.

**Comment by TheMysticS** [comment]
The alignment is nice now, even with the profile badge icon showing up.
