### ISSUE TITLE
Wrong Install Date

### ISSUE THREAD

**Issue by TheMysticS** [d4rken-org/mystic-permissions#42]
For apps installed in other profiles that show up as Twins, the install date shown is wrong.

![Screenshot_2022-07-19-18-52-26-64_ce34de6323cfaeb7a2880d42987990b1](https://user-images.githubusercontent.com/54448474/179762673-8b0982e1-3bba-4851-8841-2cefcddd51fd.jpg)

Please look into it.

**Comment by d4rken** [comment]
Hm that's the default value, seems like it does not have an install date.
I will hide the info in that case.

**Comment by TheMysticS** [comment]
YEs, the last update time will be the same for Twins. You are right, this info won't be necessary since it is already showing under the app in the Main Profile.
