### ISSUE TITLE
Installation and Updation details for Apps 

### ISSUE THREAD

**Issue by TheMysticS** [d4rken-org/mystic-permissions#43]
For all apps, can you also include information on date installed and last updated as follows:

![iMarkup_20220719_191016](https://user-images.githubusercontent.com/54448474/179764697-fced005e-95ac-4f02-84fe-74dce5d03839.jpg)

**Comment by d4rken** [comment]
That won't fit in the same line, can add it as a new row though?

**Comment by TheMysticS** [comment]
That would be fine.

A single line would do, to save space. Please show the date installed on the left side and the date last updated on the right.
