### ISSUE TITLE
New Filter: Apps not in Main Profile

### ISSUE THREAD

**Issue by TheMysticS** [d4rken-org/mystic-permissions#49]
Can you create a new filter for apps that are NOT installed in the Main Profile?

And if there is a way to sort/ club them per profile, that would be great.

**Comment by d4rken** [comment]
Maybe this is the only filter that is necessary, I don't want to spam filter options.
"Show only apps in other profiles" seems sensible.

**Comment by TheMysticS** [comment]
> Maybe this is the only filter that is necessary, I don't want to spam filter options. "Show only apps in other profiles" seems sensible.

Multiple Profiles filter has its own use as mentioned in the other ticket. Unless you need the space for something else, you might as well leave this intact.

**Comment by d4rken** [comment]
Done in 17934a86574f5ac451c8ae93c0554376f428095d
