### ISSUE TITLE
Retain Sort Selection

### ISSUE THREAD

**Issue by TheMysticS** [d4rken-org/mystic-permissions#50]
On the Apps tab, apps are sorted by 'Last Updated'. If the user chooses a different sort type, clicks on any app to see details, and then returns to the main screen, apps are again sorted by 'Last Updated'.

Can you make the app keep the sort order chosen by the user? It should change only when the user changes it.

**Comment by d4rken** [comment]
Hm save across app restarts?

**Comment by TheMysticS** [comment]
That would be fine too.
