### ISSUE TITLE
Remove 'Work' from the names of apps in other profiles 

### ISSUE THREAD

**Issue by TheMysticS** [d4rken-org/mystic-permissions#58]
The names of apps installed in other profiles have now being prefixed with the word 'Work'. This can be misleading because the user may not have installed the Work Profile, but instead a multi-user.

Having 'Work' removed will also show all apps that have clones together when sorting by name.

**Comment by d4rken** [comment]
The prefix is by the system. If it's a different profile, it will give us a different prefix.

**Comment by d4rken** [comment]
Theoretically yes, practically no. It doesn't always have to be "Work", we have no idea what it could return.

**Comment by d4rken** [comment]
The name comes from the system, it's not hardcoded to "Work".
I think it makes sense to have it listed with their prefix in the list to distinguish them (and also allow text search).

**Comment by TheMysticS** [comment]
> The name comes from the system, it's not hardcoded to "Work". I think it makes sense to have it listed with their prefix in the list to distinguish them (and also allow text search).

It can't be hardcoded. Since it has returned something meaningful (and accurate), we can hope that it will do the same with multi-users too!
