### ISSUE TITLE
Work Badge in Permissions Bar

### ISSUE THREAD

**Issue by TheMysticS** [d4rken-org/mystic-permissions#61]
In the Apps tab, apps with clones or those installed in other profiles have the briefcase icon in the permissions bar.

Can you make the following changes:

1. Same colour as other enabled permissions for this badge, for apps in the main profile that have clones.

2. For apps installed in other profiles that do not have a clone in the main profile, this icon will show up in grey, i.e. it won't be invisible.

**Comment by d4rken** [comment]
> For apps installed in other profiles that do not have a clone in the main profile, this icon will show up in grey, i.e. it won't be invisible.

I like this
