### ISSUE TITLE
Apps that support ROOT features

### ISSUE THREAD

**Issue by TheMysticS** [d4rken-org/mystic-permissions#75]
Can we have a filter that lists all apps which have support for ROOT features, including those that REQUIRE root/ superuser access?

This can be useful because Magisk and similar apps only show apps that have specifically requested root access. They don't show apps that haven't requested it, but can support root features such as some file manager apps.

**Comment by d4rken** [comment]
Similar to #76, this is something that can not be reliably detected.

Root is not a permission tha apps declare.
Some time ago there was a movement to just declare it, and SuperSU supported it, but currently there isn't a way and it's not done.

So I'd consider this out of scope too. I don't want to maintain manual lists about root apps. 🤔
